
package com.fortify.schema.fws;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import xmlns.www_fortifysoftware_com.schema.wstypes.AddStatus;
import xmlns.www_fortifysoftware_com.schema.wstypes.LdapEntity;
import xmlns.www_fortifysoftware_com.schema.wstypes.MetaDataDefinition;
import xmlns.www_fortifysoftware_com.schema.wstypes.Project;
import xmlns.www_fortifysoftware_com.schema.wstypes.SdlBundleUploadStatus;
import xmlns.www_fortifysoftware_com.schema.wstypes.Status;
import xmlns.www_fortifysoftware_com.schema.wstypes.TagDefinition;
import xmlns.www_fortifysoftware_com.schema.wstypes.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-hudson-$BUILD_NUMBER-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "services", targetNamespace = "http://www.fortify.com/schema/fws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    xmlns.www_fortify_com.schema.audit.ObjectFactory.class,
    xmlns.www_fortify_com.schema.issuemanagement.ObjectFactory.class,
    xmlns.www_fortifysoftware_com.schema.activitytemplate.ObjectFactory.class,
    xmlns.www_fortifysoftware_com.schema.seed.ObjectFactory.class,
    xmlns.www_fortifysoftware_com.schema.wstypes.ObjectFactory.class,
    xmlns.www_fortifysoftware_com.schema.runtime.ObjectFactory.class,
    com.fortify.schema.fws.ObjectFactory.class,
    xmlns.www_fortifysoftware_com.schema.enumconstants.ObjectFactory.class,
    xmlns.www_fortify_com.schema.attachments.ObjectFactory.class
})
public interface Services {


    /**
     * 
     * @param mostRecentVariableHistoryListRequest
     */
    @WebMethod(operationName = "MostRecentVariableHistoryList")
    @Oneway
    public void mostRecentVariableHistoryList(
        @WebParam(name = "MostRecentVariableHistoryListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "MostRecentVariableHistoryListRequest")
        MostRecentVariableHistoryListRequest mostRecentVariableHistoryListRequest);

    /**
     * 
     * @param documentArtifactDownloadRequest
     * @return
     *     returns com.fortify.schema.fws.DocumentArtifactDownloadResponse
     */
    @WebMethod(operationName = "DocumentArtifactDownload")
    @WebResult(name = "DocumentArtifactDownloadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DocumentArtifactDownloadResponse")
    public DocumentArtifactDownloadResponse documentArtifactDownload(
        @WebParam(name = "DocumentArtifactDownloadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DocumentArtifactDownloadRequest")
        DocumentArtifactDownloadRequest documentArtifactDownloadRequest);

    /**
     * 
     * @param analysisPayloadDispatchRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AnalysisPayloadDispatch")
    @WebResult(name = "AnalysisPayloadDispatchResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisPayloadDispatchResponse")
    public Status analysisPayloadDispatch(
        @WebParam(name = "AnalysisPayloadDispatchRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisPayloadDispatchRequest")
        AnalysisPayloadDispatchRequest analysisPayloadDispatchRequest);

    /**
     * 
     * @param addCustomTagRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AddCustomTag")
    @WebResult(name = "AddCustomTagResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddCustomTagResponse")
    public Status addCustomTag(
        @WebParam(name = "AddCustomTagRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddCustomTagRequest")
        TagDefinition addCustomTagRequest);

    /**
     * 
     * @param searchLdapRequest
     * @return
     *     returns com.fortify.schema.fws.SearchLdapResponse
     */
    @WebMethod(operationName = "SearchLdap")
    @WebResult(name = "SearchLdapResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SearchLdapResponse")
    public SearchLdapResponse searchLdap(
        @WebParam(name = "SearchLdapRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SearchLdapRequest")
        SearchLdapRequest searchLdapRequest);

    /**
     * 
     * @param projectMetaDataValueRequest
     * @return
     *     returns com.fortify.schema.fws.ProjectMetaDataValueResponse
     */
    @WebMethod(operationName = "ProjectMetaDataValue")
    @WebResult(name = "ProjectMetaDataValueResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectMetaDataValueResponse")
    public ProjectMetaDataValueResponse projectMetaDataValue(
        @WebParam(name = "ProjectMetaDataValueRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectMetaDataValueRequest")
        ProjectMetaDataValueRequest projectMetaDataValueRequest);

    /**
     * 
     * @param analysisCompleteRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AnalysisComplete")
    @WebResult(name = "AnalysisCompleteResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisCompleteResponse")
    public Status analysisComplete(
        @WebParam(name = "AnalysisCompleteRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisCompleteRequest")
        AnalysisCompleteRequest analysisCompleteRequest);

    /**
     * 
     * @param personaListRequest
     * @return
     *     returns com.fortify.schema.fws.PersonaListResponse
     */
    @WebMethod(operationName = "PersonaList")
    @WebResult(name = "PersonaListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "PersonaListResponse")
    public PersonaListResponse personaList(
        @WebParam(name = "PersonaListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "PersonaListRequest")
        Object personaListRequest);

    /**
     * 
     * @param analysisPayloadRedispatchRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AnalysisPayloadRedispatch")
    @WebResult(name = "AnalysisPayloadRedispatchResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisPayloadRedispatchResponse")
    public Status analysisPayloadRedispatch(
        @WebParam(name = "AnalysisPayloadRedispatchRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisPayloadRedispatchRequest")
        AnalysisPayloadRedispatchRequest analysisPayloadRedispatchRequest);

    /**
     * 
     * @param documentArtifactUploadRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.AddStatus
     */
    @WebMethod(operationName = "DocumentArtifactUpload")
    @WebResult(name = "DocumentArtifactUploadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DocumentArtifactUploadResponse")
    public AddStatus documentArtifactUpload(
        @WebParam(name = "DocumentArtifactUploadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DocumentArtifactUploadRequest")
        DocumentArtifactUploadRequest documentArtifactUploadRequest);

    /**
     * 
     * @param migrateUserRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.AddStatus
     */
    @WebMethod(operationName = "MigrateUser")
    @WebResult(name = "MigrateUserResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "MigrateUserResponse")
    public AddStatus migrateUser(
        @WebParam(name = "MigrateUserRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "MigrateUserRequest")
        MigrateUserRequest migrateUserRequest);

    /**
     * 
     * @param submitBugRequest
     * @return
     *     returns com.fortify.schema.fws.SubmitBugResponse
     */
    @WebMethod(operationName = "SubmitBug")
    @WebResult(name = "SubmitBugResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SubmitBugResponse")
    public SubmitBugResponse submitBug(
        @WebParam(name = "SubmitBugRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SubmitBugRequest")
        SubmitBugRequest submitBugRequest);

    /**
     * 
     * @param activityTemplateAssignmentRuleListRequest
     * @return
     *     returns com.fortify.schema.fws.ActivityTemplateAssignmentRuleListResponse
     */
    @WebMethod(operationName = "ActivityTemplateAssignmentRuleList")
    @WebResult(name = "ActivityTemplateAssignmentRuleListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ActivityTemplateAssignmentRuleListResponse")
    public ActivityTemplateAssignmentRuleListResponse activityTemplateAssignmentRuleList(
        @WebParam(name = "ActivityTemplateAssignmentRuleListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ActivityTemplateAssignmentRuleListRequest")
        Object activityTemplateAssignmentRuleListRequest);

    /**
     * 
     * @param cloudOneTimeJobTokenRequest
     */
    @WebMethod(operationName = "CloudOneTimeJobToken")
    @Oneway
    public void cloudOneTimeJobToken(
        @WebParam(name = "CloudOneTimeJobTokenRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CloudOneTimeJobTokenRequest")
        CloudOneTimeJobTokenRequest cloudOneTimeJobTokenRequest);

    /**
     * 
     * @param updateAlertDefinitionAndPropagateRequest
     */
    @WebMethod(operationName = "UpdateAlertDefinitionAndPropagate")
    @Oneway
    public void updateAlertDefinitionAndPropagate(
        @WebParam(name = "UpdateAlertDefinitionAndPropagateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateAlertDefinitionAndPropagateRequest")
        UpdateAlertDefinitionAndPropagateRequest updateAlertDefinitionAndPropagateRequest);

    /**
     * 
     * @param generateReportRequest
     * @return
     *     returns com.fortify.schema.fws.GenerateReportResponse
     */
    @WebMethod(operationName = "GenerateReport")
    @WebResult(name = "GenerateReportResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "GenerateReportResponse")
    public GenerateReportResponse generateReport(
        @WebParam(name = "GenerateReportRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "GenerateReportRequest")
        GenerateReportRequest generateReportRequest);

    /**
     * 
     * @param archiveRuntimeEventRequest
     * @return
     *     returns com.fortify.schema.fws.ArchiveRuntimeEventResponse
     */
    @WebMethod(operationName = "ArchiveRuntimeEvent")
    @WebResult(name = "ArchiveRuntimeEventResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ArchiveRuntimeEventResponse")
    public ArchiveRuntimeEventResponse archiveRuntimeEvent(
        @WebParam(name = "ArchiveRuntimeEventRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ArchiveRuntimeEventRequest")
        ArchiveRuntimeEventRequest archiveRuntimeEventRequest);

    /**
     * 
     * @param measurementHistoryListForSnapshotRequest
     */
    @WebMethod(operationName = "MeasurementHistoryListForSnapshot")
    @Oneway
    public void measurementHistoryListForSnapshot(
        @WebParam(name = "MeasurementHistoryListForSnapshotRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "MeasurementHistoryListForSnapshotRequest")
        MeasurementHistoryListForSnapshotRequest measurementHistoryListForSnapshotRequest);

    /**
     * 
     * @param fprSimpleMigrateRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "FPRSimpleMigrate")
    @WebResult(name = "FPRSimpleMigrateResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "FPRSimpleMigrateResponse")
    public Status fprSimpleMigrate(
        @WebParam(name = "FPRSimpleMigrateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "FPRSimpleMigrateRequest")
        FprSimpleMigrateRequest fprSimpleMigrateRequest);

    /**
     * 
     * @param cloudCtrlUrlRequest
     * @return
     *     returns com.fortify.schema.fws.CloudCtrlUrlResponse
     */
    @WebMethod(operationName = "CloudCtrlUrl")
    @WebResult(name = "CloudCtrlUrlResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CloudCtrlUrlResponse")
    public CloudCtrlUrlResponse cloudCtrlUrl(
        @WebParam(name = "CloudCtrlUrlRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CloudCtrlUrlRequest")
        Object cloudCtrlUrlRequest);

    /**
     * 
     * @param allAlertDefinitionsListRequest
     */
    @WebMethod(operationName = "AllAlertDefinitionsList")
    @Oneway
    public void allAlertDefinitionsList(
        @WebParam(name = "AllAlertDefinitionsListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AllAlertDefinitionsListRequest")
        Object allAlertDefinitionsListRequest);

    /**
     * 
     * @param createOrUpdateProjectMetaDataValuesListRequest
     */
    @WebMethod(operationName = "CreateOrUpdateProjectMetaDataValuesList")
    @Oneway
    public void createOrUpdateProjectMetaDataValuesList(
        @WebParam(name = "CreateOrUpdateProjectMetaDataValuesListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CreateOrUpdateProjectMetaDataValuesListRequest")
        CreateOrUpdateProjectMetaDataValuesListRequest createOrUpdateProjectMetaDataValuesListRequest);

    /**
     * 
     * @param addProjectMetaDataDefinitionRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AddProjectMetaDataDefinition")
    @WebResult(name = "AddProjectMetaDataDefinitionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddProjectMetaDataDefinitionResponse")
    public Status addProjectMetaDataDefinition(
        @WebParam(name = "AddProjectMetaDataDefinitionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddProjectMetaDataDefinitionRequest")
        MetaDataDefinition addProjectMetaDataDefinitionRequest);

    /**
     * 
     * @param addUserRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.AddStatus
     */
    @WebMethod(operationName = "AddUser")
    @WebResult(name = "AddUserResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddUserResponse")
    public AddStatus addUser(
        @WebParam(name = "AddUserRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddUserRequest")
        User addUserRequest);

    /**
     * 
     * @param deleteCustomTagRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "DeleteCustomTag")
    @WebResult(name = "DeleteCustomTagResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteCustomTagResponse")
    public Status deleteCustomTag(
        @WebParam(name = "DeleteCustomTagRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteCustomTagRequest")
        DeleteCustomTagRequest deleteCustomTagRequest);

    /**
     * 
     * @param customTagListForProjectVersionRequest
     */
    @WebMethod(operationName = "CustomTagListForProjectVersion")
    @Oneway
    public void customTagListForProjectVersion(
        @WebParam(name = "CustomTagListForProjectVersionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CustomTagListForProjectVersionRequest")
        CustomTagListForProjectVersionRequest customTagListForProjectVersionRequest);

    /**
     * 
     * @param groupingValuesRequest
     * @return
     *     returns com.fortify.schema.fws.GroupingValuesResponse
     */
    @WebMethod(operationName = "GroupingValues")
    @WebResult(name = "GroupingValuesResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "GroupingValuesResponse")
    public GroupingValuesResponse groupingValues(
        @WebParam(name = "GroupingValuesRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "GroupingValuesRequest")
        GroupingValuesRequest groupingValuesRequest);

    /**
     * 
     * @param snapshotMostRecentFirstDateRequest
     */
    @WebMethod(operationName = "SnapshotMostRecentFirstDate")
    @Oneway
    public void snapshotMostRecentFirstDate(
        @WebParam(name = "SnapshotMostRecentFirstDateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SnapshotMostRecentFirstDateRequest")
        SnapshotMostRecentFirstDateRequest snapshotMostRecentFirstDateRequest);

    /**
     * 
     * @param savedReportDownloadRequest
     * @return
     *     returns com.fortify.schema.fws.SavedReportDownloadResponse
     */
    @WebMethod(operationName = "SavedReportDownload")
    @WebResult(name = "SavedReportDownloadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SavedReportDownloadResponse")
    public SavedReportDownloadResponse savedReportDownload(
        @WebParam(name = "SavedReportDownloadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SavedReportDownloadRequest")
        SavedReportDownloadRequest savedReportDownloadRequest);

    /**
     * 
     * @param savedReportListForProjectVersionRequest
     * @return
     *     returns com.fortify.schema.fws.SavedReportListForProjectVersionResponse
     */
    @WebMethod(operationName = "SavedReportListForProjectVersion")
    @WebResult(name = "SavedReportListForProjectVersionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SavedReportListForProjectVersionResponse")
    public SavedReportListForProjectVersionResponse savedReportListForProjectVersion(
        @WebParam(name = "SavedReportListForProjectVersionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SavedReportListForProjectVersionRequest")
        SavedReportListForProjectVersionRequest savedReportListForProjectVersionRequest);

    /**
     * 
     * @param savedReportListRequest
     * @return
     *     returns com.fortify.schema.fws.SavedReportListResponse
     */
    @WebMethod(operationName = "SavedReportList")
    @WebResult(name = "SavedReportListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SavedReportListResponse")
    public SavedReportListResponse savedReportList(
        @WebParam(name = "SavedReportListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SavedReportListRequest")
        Object savedReportListRequest);

    /**
     * 
     * @param projectMetaDataValuesListRequest
     * @return
     *     returns com.fortify.schema.fws.ProjectMetaDataValuesListResponse
     */
    @WebMethod(operationName = "ProjectMetaDataValuesList")
    @WebResult(name = "ProjectMetaDataValuesListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectMetaDataValuesListResponse")
    public ProjectMetaDataValuesListResponse projectMetaDataValuesList(
        @WebParam(name = "ProjectMetaDataValuesListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectMetaDataValuesListRequest")
        ProjectMetaDataValuesListRequest projectMetaDataValuesListRequest);

    /**
     * 
     * @param deleteProjectRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "DeleteProject")
    @WebResult(name = "DeleteProjectResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteProjectResponse")
    public Status deleteProject(
        @WebParam(name = "DeleteProjectRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteProjectRequest")
        DeleteProjectRequest deleteProjectRequest);

    /**
     * 
     * @param projectTemplateDownloadRequest
     * @return
     *     returns com.fortify.schema.fws.ProjectTemplateDownloadResponse
     */
    @WebMethod(operationName = "ProjectTemplateDownload")
    @WebResult(name = "ProjectTemplateDownloadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectTemplateDownloadResponse")
    public ProjectTemplateDownloadResponse projectTemplateDownload(
        @WebParam(name = "ProjectTemplateDownloadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectTemplateDownloadRequest")
        ProjectTemplateDownloadRequest projectTemplateDownloadRequest);

    /**
     * 
     * @param createAuditSessionRequest
     * @return
     *     returns com.fortify.schema.fws.CreateAuditSessionResponse
     */
    @WebMethod(operationName = "CreateAuditSession")
    @WebResult(name = "CreateAuditSessionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CreateAuditSessionResponse")
    public CreateAuditSessionResponse createAuditSession(
        @WebParam(name = "CreateAuditSessionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CreateAuditSessionRequest")
        CreateAuditSessionRequest createAuditSessionRequest);

    /**
     * 
     * @param artifactDownloadRequest
     * @return
     *     returns com.fortify.schema.fws.ArtifactDownloadResponse
     */
    @WebMethod(operationName = "ArtifactDownload")
    @WebResult(name = "ArtifactDownloadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ArtifactDownloadResponse")
    public ArtifactDownloadResponse artifactDownload(
        @WebParam(name = "ArtifactDownloadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ArtifactDownloadRequest")
        ArtifactDownloadRequest artifactDownloadRequest);

    /**
     * 
     * @param analysisStatusUpdateRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AnalysisStatusUpdate")
    @WebResult(name = "AnalysisStatusUpdateResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisStatusUpdateResponse")
    public Status analysisStatusUpdate(
        @WebParam(name = "AnalysisStatusUpdateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisStatusUpdateRequest")
        AnalysisStatusUpdateRequest analysisStatusUpdateRequest);

    /**
     * 
     * @param jobListRequest
     * @return
     *     returns com.fortify.schema.fws.JobListResponse
     */
    @WebMethod(operationName = "JobList")
    @WebResult(name = "JobListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "JobListResponse")
    public JobListResponse jobList(
        @WebParam(name = "JobListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "JobListRequest")
        Object jobListRequest);

    /**
     * 
     * @param projectTemplateListRequest
     * @return
     *     returns com.fortify.schema.fws.ProjectTemplateListResponse
     */
    @WebMethod(operationName = "ProjectTemplateList")
    @WebResult(name = "ProjectTemplateListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectTemplateListResponse")
    public ProjectTemplateListResponse projectTemplateList(
        @WebParam(name = "ProjectTemplateListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectTemplateListRequest")
        Object projectTemplateListRequest);

    /**
     * 
     * @param batchCreateUpdateAndAssignCustomTagsRequest
     * @return
     *     returns com.fortify.schema.fws.BatchCreateUpdateAndAssignCustomTagsResponse
     */
    @WebMethod(operationName = "BatchCreateUpdateAndAssignCustomTags")
    @WebResult(name = "BatchCreateUpdateAndAssignCustomTagsResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "BatchCreateUpdateAndAssignCustomTagsResponse")
    public BatchCreateUpdateAndAssignCustomTagsResponse batchCreateUpdateAndAssignCustomTags(
        @WebParam(name = "BatchCreateUpdateAndAssignCustomTagsRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "BatchCreateUpdateAndAssignCustomTagsRequest")
        BatchCreateUpdateAndAssignCustomTagsRequest batchCreateUpdateAndAssignCustomTagsRequest);

    /**
     * 
     * @param assignToProjectVersionRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AssignToProjectVersion")
    @WebResult(name = "AssignToProjectVersionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AssignToProjectVersionResponse")
    public Status assignToProjectVersion(
        @WebParam(name = "AssignToProjectVersionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AssignToProjectVersionRequest")
        AssignToProjectVersionRequest assignToProjectVersionRequest);

    /**
     * 
     * @param activeProjectVersionListRequest
     * @return
     *     returns com.fortify.schema.fws.ActiveProjectVersionListResponse
     */
    @WebMethod(operationName = "ActiveProjectVersionList")
    @WebResult(name = "ActiveProjectVersionListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ActiveProjectVersionListResponse")
    public ActiveProjectVersionListResponse activeProjectVersionList(
        @WebParam(name = "ActiveProjectVersionListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ActiveProjectVersionListRequest")
        Object activeProjectVersionListRequest);

    /**
     * 
     * @param assignLdapEntityPermissionsRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AssignLdapEntityPermissions")
    @WebResult(name = "AssignLdapEntityPermissionsResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AssignLdapEntityPermissionsResponse")
    public Status assignLdapEntityPermissions(
        @WebParam(name = "AssignLdapEntityPermissionsRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AssignLdapEntityPermissionsRequest")
        LdapEntity assignLdapEntityPermissionsRequest);

    /**
     * 
     * @param measurementHistoryListForProjectVersionAndMeasurementAgentRequest
     */
    @WebMethod(operationName = "MeasurementHistoryListForProjectVersionAndMeasurementAgent")
    @Oneway
    public void measurementHistoryListForProjectVersionAndMeasurementAgent(
        @WebParam(name = "MeasurementHistoryListForProjectVersionAndMeasurementAgentRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "MeasurementHistoryListForProjectVersionAndMeasurementAgentRequest")
        MeasurementHistoryListForProjectVersionAndMeasurementAgentRequest measurementHistoryListForProjectVersionAndMeasurementAgentRequest);

    /**
     * 
     * @param jobStatusRequest
     * @return
     *     returns com.fortify.schema.fws.JobStatusResponse
     */
    @WebMethod(operationName = "JobStatus")
    @WebResult(name = "JobStatusResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "JobStatusResponse")
    public JobStatusResponse jobStatus(
        @WebParam(name = "JobStatusRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "JobStatusRequest")
        JobStatusRequest jobStatusRequest);

    /**
     * 
     * @param variableHistoryListForVariableRequest
     */
    @WebMethod(operationName = "VariableHistoryListForVariable")
    @Oneway
    public void variableHistoryListForVariable(
        @WebParam(name = "VariableHistoryListForVariableRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "VariableHistoryListForVariableRequest")
        VariableHistoryListForVariableRequest variableHistoryListForVariableRequest);

    /**
     * 
     * @param equationVariableListRequest
     * @return
     *     returns com.fortify.schema.fws.EquationVariableListResponse
     */
    @WebMethod(operationName = "EquationVariableList")
    @WebResult(name = "EquationVariableListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "EquationVariableListResponse")
    public EquationVariableListResponse equationVariableList(
        @WebParam(name = "EquationVariableListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "EquationVariableListRequest")
        Object equationVariableListRequest);

    /**
     * 
     * @param auditViewRequest
     * @return
     *     returns com.fortify.schema.fws.AuditViewResponse
     */
    @WebMethod(operationName = "AuditView")
    @WebResult(name = "AuditViewResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AuditViewResponse")
    public AuditViewResponse auditView(
        @WebParam(name = "AuditViewRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AuditViewRequest")
        AuditViewRequest auditViewRequest);

    /**
     * 
     * @param projectListRequest
     * @return
     *     returns com.fortify.schema.fws.ProjectListResponse
     */
    @WebMethod(operationName = "ProjectList")
    @WebResult(name = "ProjectListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectListResponse")
    public ProjectListResponse projectList(
        @WebParam(name = "ProjectListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectListRequest")
        Object projectListRequest);

    /**
     * 
     * @param deleteUserRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "DeleteUser")
    @WebResult(name = "DeleteUserResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteUserResponse")
    public Status deleteUser(
        @WebParam(name = "DeleteUserRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteUserRequest")
        DeleteUserRequest deleteUserRequest);

    /**
     * 
     * @param contentBundleUploadRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "ContentBundleUpload")
    @WebResult(name = "ContentBundleUploadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ContentBundleUploadResponse")
    public Status contentBundleUpload(
        @WebParam(name = "ContentBundleUploadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ContentBundleUploadRequest")
        ContentBundleUploadRequest contentBundleUploadRequest);

    /**
     * 
     * @param issueListRequest
     * @return
     *     returns com.fortify.schema.fws.IssueListResponse
     */
    @WebMethod(operationName = "IssueList")
    @WebResult(name = "IssueListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "IssueListResponse")
    public IssueListResponse issueList(
        @WebParam(name = "IssueListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "IssueListRequest")
        IssueListRequest issueListRequest);

    /**
     * 
     * @param updateUserRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "UpdateUser")
    @WebResult(name = "UpdateUserResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateUserResponse")
    public Status updateUser(
        @WebParam(name = "UpdateUserRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateUserRequest")
        User updateUserRequest);

    /**
     * 
     * @param assignCustomTagsToProjectTemplateRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AssignCustomTagsToProjectTemplate")
    @WebResult(name = "AssignCustomTagsToProjectTemplateResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AssignCustomTagsToProjectTemplateResponse")
    public Status assignCustomTagsToProjectTemplate(
        @WebParam(name = "AssignCustomTagsToProjectTemplateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AssignCustomTagsToProjectTemplateRequest")
        AssignCustomTagsToProjectTemplateRequest assignCustomTagsToProjectTemplateRequest);

    /**
     * 
     * @param getSingleUseFPRDownloadTokenRequest
     */
    @WebMethod(operationName = "GetSingleUseFPRDownloadToken")
    @Oneway
    public void getSingleUseFPRDownloadToken(
        @WebParam(name = "GetSingleUseFPRDownloadTokenRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "GetSingleUseFPRDownloadTokenRequest")
        GetSingleUseFprDownloadTokenRequest getSingleUseFPRDownloadTokenRequest);

    /**
     * 
     * @param userListRequest
     * @return
     *     returns com.fortify.schema.fws.UserListResponse
     */
    @WebMethod(operationName = "UserList")
    @WebResult(name = "UserListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UserListResponse")
    public UserListResponse userList(
        @WebParam(name = "UserListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UserListRequest")
        Object userListRequest);

    /**
     * 
     * @param projectMetaDataDefinitionByGuidRequest
     */
    @WebMethod(operationName = "ProjectMetaDataDefinitionByGuid")
    @Oneway
    public void projectMetaDataDefinitionByGuid(
        @WebParam(name = "ProjectMetaDataDefinitionByGuidRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectMetaDataDefinitionByGuidRequest")
        ProjectMetaDataDefinitionByGuidRequest projectMetaDataDefinitionByGuidRequest);

    /**
     * 
     * @param measurementHistoryListForSnapshotAndMeasurementAgentsRequest
     */
    @WebMethod(operationName = "MeasurementHistoryListForSnapshotAndMeasurementAgents")
    @Oneway
    public void measurementHistoryListForSnapshotAndMeasurementAgents(
        @WebParam(name = "MeasurementHistoryListForSnapshotAndMeasurementAgentsRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "MeasurementHistoryListForSnapshotAndMeasurementAgentsRequest")
        MeasurementHistoryListForSnapshotAndMeasurementAgentsRequest measurementHistoryListForSnapshotAndMeasurementAgentsRequest);

    /**
     * 
     * @param measurementHistoryListRequest
     * @return
     *     returns com.fortify.schema.fws.MeasurementHistoryListResponse
     */
    @WebMethod(operationName = "MeasurementHistoryList")
    @WebResult(name = "MeasurementHistoryListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "MeasurementHistoryListResponse")
    public MeasurementHistoryListResponse measurementHistoryList(
        @WebParam(name = "MeasurementHistoryListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "MeasurementHistoryListRequest")
        MeasurementHistoryListRequest measurementHistoryListRequest);

    /**
     * 
     * @param fprDownloadRequest
     * @return
     *     returns com.fortify.schema.fws.FprDownloadResponse
     */
    @WebMethod(operationName = "FPRDownload")
    @WebResult(name = "FPRDownloadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "FPRDownloadResponse")
    public FprDownloadResponse fprDownload(
        @WebParam(name = "FPRDownloadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "FPRDownloadRequest")
        FprDownloadRequest fprDownloadRequest);

    /**
     * 
     * @param authenticationTokenListRequest
     * @return
     *     returns com.fortify.schema.fws.AuthenticationTokenListResponse
     */
    @WebMethod(operationName = "AuthenticationTokenList")
    @WebResult(name = "AuthenticationTokenListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AuthenticationTokenListResponse")
    public AuthenticationTokenListResponse authenticationTokenList(
        @WebParam(name = "AuthenticationTokenListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AuthenticationTokenListRequest")
        Object authenticationTokenListRequest);

    /**
     * 
     * @param currentUserPermissionTemplateListRequest
     * @return
     *     returns com.fortify.schema.fws.CurrentUserPermissionTemplateListResponse
     */
    @WebMethod(operationName = "CurrentUserPermissionTemplateList")
    @WebResult(name = "CurrentUserPermissionTemplateListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CurrentUserPermissionTemplateListResponse")
    public CurrentUserPermissionTemplateListResponse currentUserPermissionTemplateList(
        @WebParam(name = "CurrentUserPermissionTemplateListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CurrentUserPermissionTemplateListRequest")
        Object currentUserPermissionTemplateListRequest);

    /**
     * 
     * @param analysisUploadReleaseRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AnalysisUploadRelease")
    @WebResult(name = "AnalysisUploadReleaseResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisUploadReleaseResponse")
    public Status analysisUploadRelease(
        @WebParam(name = "AnalysisUploadReleaseRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisUploadReleaseRequest")
        AnalysisUploadReleaseRequest analysisUploadReleaseRequest);

    /**
     * 
     * @param updateAlertDefinitionForSelfRequest
     */
    @WebMethod(operationName = "UpdateAlertDefinitionForSelf")
    @Oneway
    public void updateAlertDefinitionForSelf(
        @WebParam(name = "UpdateAlertDefinitionForSelfRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateAlertDefinitionForSelfRequest")
        UpdateAlertDefinitionForSelfRequest updateAlertDefinitionForSelfRequest);

    /**
     * 
     * @param addRuntimeApplicationRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.AddStatus
     */
    @WebMethod(operationName = "AddRuntimeApplication")
    @WebResult(name = "AddRuntimeApplicationResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddRuntimeApplicationResponse")
    public AddStatus addRuntimeApplication(
        @WebParam(name = "AddRuntimeApplicationRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddRuntimeApplicationRequest")
        AddRuntimeApplicationRequest addRuntimeApplicationRequest);

    /**
     * 
     * @param createAlertDefinitionAndPropagateRequest
     */
    @WebMethod(operationName = "CreateAlertDefinitionAndPropagate")
    @Oneway
    public void createAlertDefinitionAndPropagate(
        @WebParam(name = "CreateAlertDefinitionAndPropagateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CreateAlertDefinitionAndPropagateRequest")
        CreateAlertDefinitionAndPropagateRequest createAlertDefinitionAndPropagateRequest);

    /**
     * 
     * @param updateProjectMetaDataDefinitionRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "UpdateProjectMetaDataDefinition")
    @WebResult(name = "UpdateProjectMetaDataDefinitionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateProjectMetaDataDefinitionResponse")
    public Status updateProjectMetaDataDefinition(
        @WebParam(name = "UpdateProjectMetaDataDefinitionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateProjectMetaDataDefinitionRequest")
        MetaDataDefinition updateProjectMetaDataDefinitionRequest);

    /**
     * 
     * @param deleteRuntimeApplicationRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "DeleteRuntimeApplication")
    @WebResult(name = "DeleteRuntimeApplicationResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteRuntimeApplicationResponse")
    public Status deleteRuntimeApplication(
        @WebParam(name = "DeleteRuntimeApplicationRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteRuntimeApplicationRequest")
        DeleteRuntimeApplicationRequest deleteRuntimeApplicationRequest);

    /**
     * 
     * @param descriptionAndRecommendationRequest
     * @return
     *     returns com.fortify.schema.fws.DescriptionAndRecommendationResponse
     */
    @WebMethod(operationName = "DescriptionAndRecommendation")
    @WebResult(name = "DescriptionAndRecommendationResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DescriptionAndRecommendationResponse")
    public DescriptionAndRecommendationResponse descriptionAndRecommendation(
        @WebParam(name = "DescriptionAndRecommendationRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DescriptionAndRecommendationRequest")
        DescriptionAndRecommendationRequest descriptionAndRecommendationRequest);

    /**
     * 
     * @param updateCustomTagRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "UpdateCustomTag")
    @WebResult(name = "UpdateCustomTagResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateCustomTagResponse")
    public Status updateCustomTag(
        @WebParam(name = "UpdateCustomTagRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateCustomTagRequest")
        TagDefinition updateCustomTagRequest);

    /**
     * 
     * @param templateAssignmentRuleListRequest
     * @return
     *     returns com.fortify.schema.fws.TemplateAssignmentRuleListResponse
     */
    @WebMethod(operationName = "TemplateAssignmentRuleList")
    @WebResult(name = "TemplateAssignmentRuleListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "TemplateAssignmentRuleListResponse")
    public TemplateAssignmentRuleListResponse templateAssignmentRuleList(
        @WebParam(name = "TemplateAssignmentRuleListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "TemplateAssignmentRuleListRequest")
        Object templateAssignmentRuleListRequest);

    /**
     * 
     * @param fprUploadRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "FPRUpload")
    @WebResult(name = "FPRUploadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "FPRUploadResponse")
    public Status fprUpload(
        @WebParam(name = "FPRUploadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "FPRUploadRequest")
        FprUploadRequest fprUploadRequest);

    /**
     * 
     * @param uploadRequest
     * @return
     *     returns com.fortify.schema.fws.UploadResponse
     */
    @WebMethod(operationName = "Upload")
    @WebResult(name = "UploadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UploadResponse")
    public UploadResponse upload(
        @WebParam(name = "UploadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UploadRequest")
        Status uploadRequest);

    /**
     * 
     * @param documentDefinitionListRequest
     * @return
     *     returns com.fortify.schema.fws.DocumentDefinitionListResponse
     */
    @WebMethod(operationName = "DocumentDefinitionList")
    @WebResult(name = "DocumentDefinitionListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DocumentDefinitionListResponse")
    public DocumentDefinitionListResponse documentDefinitionList(
        @WebParam(name = "DocumentDefinitionListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DocumentDefinitionListRequest")
        Object documentDefinitionListRequest);

    /**
     * 
     * @param projectTemplateUploadRequest
     * @return
     *     returns com.fortify.schema.fws.ProjectTemplateUploadResponse
     */
    @WebMethod(operationName = "ProjectTemplateUpload")
    @WebResult(name = "ProjectTemplateUploadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectTemplateUploadResponse")
    public ProjectTemplateUploadResponse projectTemplateUpload(
        @WebParam(name = "ProjectTemplateUploadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectTemplateUploadRequest")
        ProjectTemplateUploadRequest projectTemplateUploadRequest);

    /**
     * 
     * @param permissionTemplateListRequest
     * @return
     *     returns com.fortify.schema.fws.PermissionTemplateListResponse
     */
    @WebMethod(operationName = "PermissionTemplateList")
    @WebResult(name = "PermissionTemplateListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "PermissionTemplateListResponse")
    public PermissionTemplateListResponse permissionTemplateList(
        @WebParam(name = "PermissionTemplateListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "PermissionTemplateListRequest")
        Object permissionTemplateListRequest);

    /**
     * 
     * @param purgeProjectVersionRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "PurgeProjectVersion")
    @WebResult(name = "PurgeProjectVersionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "PurgeProjectVersionResponse")
    public Status purgeProjectVersion(
        @WebParam(name = "PurgeProjectVersionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "PurgeProjectVersionRequest")
        PurgeProjectVersionRequest purgeProjectVersionRequest);

    /**
     * 
     * @param analysisPayloadDownloadRequest
     * @return
     *     returns com.fortify.schema.fws.AnalysisPayloadDownloadResponse
     */
    @WebMethod(operationName = "AnalysisPayloadDownload")
    @WebResult(name = "AnalysisPayloadDownloadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisPayloadDownloadResponse")
    public AnalysisPayloadDownloadResponse analysisPayloadDownload(
        @WebParam(name = "AnalysisPayloadDownloadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisPayloadDownloadRequest")
        AnalysisPayloadDownloadRequest analysisPayloadDownloadRequest);

    /**
     * 
     * @param deleteRequest
     * @return
     *     returns com.fortify.schema.fws.DeleteResponse
     */
    @WebMethod(operationName = "Delete")
    @WebResult(name = "DeleteResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteResponse")
    public DeleteResponse delete(
        @WebParam(name = "DeleteRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteRequest")
        Status deleteRequest);

    /**
     * 
     * @param analysisPayloadUploadRequest
     * @return
     *     returns com.fortify.schema.fws.AnalysisPayloadUploadResponse
     */
    @WebMethod(operationName = "AnalysisPayloadUpload")
    @WebResult(name = "AnalysisPayloadUploadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisPayloadUploadResponse")
    public AnalysisPayloadUploadResponse analysisPayloadUpload(
        @WebParam(name = "AnalysisPayloadUploadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisPayloadUploadRequest")
        AnalysisPayloadUploadRequest analysisPayloadUploadRequest);

    /**
     * 
     * @param licenseCapabilityListRequest
     * @return
     *     returns com.fortify.schema.fws.LicenseCapabilityListResponse
     */
    @WebMethod(operationName = "LicenseCapabilityList")
    @WebResult(name = "LicenseCapabilityListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "LicenseCapabilityListResponse")
    public LicenseCapabilityListResponse licenseCapabilityList(
        @WebParam(name = "LicenseCapabilityListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "LicenseCapabilityListRequest")
        Object licenseCapabilityListRequest);

    /**
     * 
     * @param savedReportByIdRequest
     * @return
     *     returns com.fortify.schema.fws.SavedReportByIdResponse
     */
    @WebMethod(operationName = "SavedReportById")
    @WebResult(name = "SavedReportByIdResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SavedReportByIdResponse")
    public SavedReportByIdResponse savedReportById(
        @WebParam(name = "SavedReportByIdRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SavedReportByIdRequest")
        SavedReportByIdRequest savedReportByIdRequest);

    /**
     * 
     * @param getAuthenticationTokenRequest
     * @return
     *     returns com.fortify.schema.fws.GetAuthenticationTokenResponse
     */
    @WebMethod(operationName = "GetAuthenticationToken")
    @WebResult(name = "GetAuthenticationTokenResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "GetAuthenticationTokenResponse")
    public GetAuthenticationTokenResponse getAuthenticationToken(
        @WebParam(name = "GetAuthenticationTokenRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "GetAuthenticationTokenRequest")
        GetAuthenticationTokenRequest getAuthenticationTokenRequest);

    /**
     * 
     * @param archiveRuntimeEventsInDateRangeRequest
     */
    @WebMethod(operationName = "ArchiveRuntimeEventsInDateRange")
    @Oneway
    public void archiveRuntimeEventsInDateRange(
        @WebParam(name = "ArchiveRuntimeEventsInDateRangeRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ArchiveRuntimeEventsInDateRangeRequest")
        ArchiveRuntimeEventsInDateRangeRequest archiveRuntimeEventsInDateRangeRequest);

    /**
     * 
     * @param documentTemplateDownloadRequest
     * @return
     *     returns com.fortify.schema.fws.DocumentTemplateDownloadResponse
     */
    @WebMethod(operationName = "DocumentTemplateDownload")
    @WebResult(name = "DocumentTemplateDownloadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DocumentTemplateDownloadResponse")
    public DocumentTemplateDownloadResponse documentTemplateDownload(
        @WebParam(name = "DocumentTemplateDownloadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DocumentTemplateDownloadRequest")
        DocumentTemplateDownloadRequest documentTemplateDownloadRequest);

    /**
     * 
     * @param requirementTemplateListRequest
     * @return
     *     returns com.fortify.schema.fws.RequirementTemplateListResponse
     */
    @WebMethod(operationName = "RequirementTemplateList")
    @WebResult(name = "RequirementTemplateListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RequirementTemplateListResponse")
    public RequirementTemplateListResponse requirementTemplateList(
        @WebParam(name = "RequirementTemplateListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RequirementTemplateListRequest")
        Object requirementTemplateListRequest);

    /**
     * 
     * @param customTagListForProjectTemplateRequest
     */
    @WebMethod(operationName = "CustomTagListForProjectTemplate")
    @Oneway
    public void customTagListForProjectTemplate(
        @WebParam(name = "CustomTagListForProjectTemplateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CustomTagListForProjectTemplateRequest")
        CustomTagListForProjectTemplateRequest customTagListForProjectTemplateRequest);

    /**
     * 
     * @param assignToRuntimeApplicationRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AssignToRuntimeApplication")
    @WebResult(name = "AssignToRuntimeApplicationResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AssignToRuntimeApplicationResponse")
    public Status assignToRuntimeApplication(
        @WebParam(name = "AssignToRuntimeApplicationRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AssignToRuntimeApplicationRequest")
        AssignToRuntimeApplicationRequest assignToRuntimeApplicationRequest);

    /**
     * 
     * @param variableHistoryListForProjectVersionAndVariableRequest
     */
    @WebMethod(operationName = "VariableHistoryListForProjectVersionAndVariable")
    @Oneway
    public void variableHistoryListForProjectVersionAndVariable(
        @WebParam(name = "VariableHistoryListForProjectVersionAndVariableRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "VariableHistoryListForProjectVersionAndVariableRequest")
        VariableHistoryListForProjectVersionAndVariableRequest variableHistoryListForProjectVersionAndVariableRequest);

    /**
     * 
     * @param activityListRequest
     * @return
     *     returns com.fortify.schema.fws.ActivityListResponse
     */
    @WebMethod(operationName = "ActivityList")
    @WebResult(name = "ActivityListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ActivityListResponse")
    public ActivityListResponse activityList(
        @WebParam(name = "ActivityListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ActivityListRequest")
        Object activityListRequest);

    /**
     * 
     * @param invalidateTokenRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "InvalidateToken")
    @WebResult(name = "InvalidateTokenResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "InvalidateTokenResponse")
    public Status invalidateToken(
        @WebParam(name = "InvalidateTokenRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "InvalidateTokenRequest")
        InvalidateTokenRequest invalidateTokenRequest);

    /**
     * 
     * @param traceNodesRequest
     * @return
     *     returns com.fortify.schema.fws.TraceNodesResponse
     */
    @WebMethod(operationName = "TraceNodes")
    @WebResult(name = "TraceNodesResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "TraceNodesResponse")
    public TraceNodesResponse traceNodes(
        @WebParam(name = "TraceNodesRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "TraceNodesRequest")
        TraceNodesRequest traceNodesRequest);

    /**
     * 
     * @param runtimeEventArchiveDownloadRequest
     * @return
     *     returns com.fortify.schema.fws.RuntimeEventArchiveDownloadResponse
     */
    @WebMethod(operationName = "RuntimeEventArchiveDownload")
    @WebResult(name = "RuntimeEventArchiveDownloadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RuntimeEventArchiveDownloadResponse")
    public RuntimeEventArchiveDownloadResponse runtimeEventArchiveDownload(
        @WebParam(name = "RuntimeEventArchiveDownloadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RuntimeEventArchiveDownloadRequest")
        RuntimeEventArchiveDownloadRequest runtimeEventArchiveDownloadRequest);

    /**
     * 
     * @param snapshotsForProjectVersionRequest
     */
    @WebMethod(operationName = "SnapshotsForProjectVersion")
    @Oneway
    public void snapshotsForProjectVersion(
        @WebParam(name = "SnapshotsForProjectVersionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SnapshotsForProjectVersionRequest")
        SnapshotsForProjectVersionRequest snapshotsForProjectVersionRequest);

    /**
     * 
     * @param reportDefinitionListRequest
     * @return
     *     returns com.fortify.schema.fws.ReportDefinitionListResponse
     */
    @WebMethod(operationName = "ReportDefinitionList")
    @WebResult(name = "ReportDefinitionListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ReportDefinitionListResponse")
    public ReportDefinitionListResponse reportDefinitionList(
        @WebParam(name = "ReportDefinitionListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ReportDefinitionListRequest")
        ReportDefinitionListRequest reportDefinitionListRequest);

    /**
     * 
     * @param analysisUploadDeleteRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AnalysisUploadDelete")
    @WebResult(name = "AnalysisUploadDeleteResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisUploadDeleteResponse")
    public Status analysisUploadDelete(
        @WebParam(name = "AnalysisUploadDeleteRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AnalysisUploadDeleteRequest")
        AnalysisUploadDeleteRequest analysisUploadDeleteRequest);

    /**
     * 
     * @param variableHistoryListForSnapshotRequest
     */
    @WebMethod(operationName = "VariableHistoryListForSnapshot")
    @Oneway
    public void variableHistoryListForSnapshot(
        @WebParam(name = "VariableHistoryListForSnapshotRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "VariableHistoryListForSnapshotRequest")
        VariableHistoryListForSnapshotRequest variableHistoryListForSnapshotRequest);

    /**
     * 
     * @param registeredLdapEntityListRequest
     * @return
     *     returns com.fortify.schema.fws.RegisteredLdapEntityListResponse
     */
    @WebMethod(operationName = "RegisteredLdapEntityList")
    @WebResult(name = "RegisteredLdapEntityListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RegisteredLdapEntityListResponse")
    public RegisteredLdapEntityListResponse registeredLdapEntityList(
        @WebParam(name = "RegisteredLdapEntityListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RegisteredLdapEntityListRequest")
        Object registeredLdapEntityListRequest);

    /**
     * 
     * @param variableHistoryListForSnapshotAndVariablesRequest
     */
    @WebMethod(operationName = "VariableHistoryListForSnapshotAndVariables")
    @Oneway
    public void variableHistoryListForSnapshotAndVariables(
        @WebParam(name = "VariableHistoryListForSnapshotAndVariablesRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "VariableHistoryListForSnapshotAndVariablesRequest")
        VariableHistoryListForSnapshotAndVariablesRequest variableHistoryListForSnapshotAndVariablesRequest);

    /**
     * 
     * @param snapshotsForProjectVersionAndPriorToDateRequest
     */
    @WebMethod(operationName = "SnapshotsForProjectVersionAndPriorToDate")
    @Oneway
    public void snapshotsForProjectVersionAndPriorToDate(
        @WebParam(name = "SnapshotsForProjectVersionAndPriorToDateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SnapshotsForProjectVersionAndPriorToDateRequest")
        SnapshotsForProjectVersionAndPriorToDateRequest snapshotsForProjectVersionAndPriorToDateRequest);

    /**
     * 
     * @param templateAssignmentRuleBatchUpdateRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "TemplateAssignmentRuleBatchUpdate")
    @WebResult(name = "TemplateAssignmentRuleBatchUpdateResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "TemplateAssignmentRuleBatchUpdateResponse")
    public Status templateAssignmentRuleBatchUpdate(
        @WebParam(name = "TemplateAssignmentRuleBatchUpdateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "TemplateAssignmentRuleBatchUpdateRequest")
        TemplateAssignmentRuleBatchUpdateRequest templateAssignmentRuleBatchUpdateRequest);

    /**
     * 
     * @param deleteSavedReportsRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "DeleteSavedReports")
    @WebResult(name = "DeleteSavedReportsResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteSavedReportsResponse")
    public Status deleteSavedReports(
        @WebParam(name = "DeleteSavedReportsRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteSavedReportsRequest")
        DeleteSavedReportsRequest deleteSavedReportsRequest);

    /**
     * 
     * @param updateRequest
     * @return
     *     returns com.fortify.schema.fws.UpdateResponse
     */
    @WebMethod(operationName = "Update")
    @WebResult(name = "UpdateResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateResponse")
    public UpdateResponse update(
        @WebParam(name = "UpdateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateRequest")
        Status updateRequest);

    /**
     * 
     * @param projectMetaDataDefinitionsListRequest
     * @return
     *     returns com.fortify.schema.fws.ProjectMetaDataDefinitionsListResponse
     */
    @WebMethod(operationName = "ProjectMetaDataDefinitionsList")
    @WebResult(name = "ProjectMetaDataDefinitionsListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectMetaDataDefinitionsListResponse")
    public ProjectMetaDataDefinitionsListResponse projectMetaDataDefinitionsList(
        @WebParam(name = "ProjectMetaDataDefinitionsListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ProjectMetaDataDefinitionsListRequest")
        ProjectMetaDataDefinitionsListRequest projectMetaDataDefinitionsListRequest);

    /**
     * 
     * @param myAlertDefinitionsListRequest
     */
    @WebMethod(operationName = "MyAlertDefinitionsList")
    @Oneway
    public void myAlertDefinitionsList(
        @WebParam(name = "MyAlertDefinitionsListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "MyAlertDefinitionsListRequest")
        Object myAlertDefinitionsListRequest);

    /**
     * 
     * @param updateProjectRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "UpdateProject")
    @WebResult(name = "UpdateProjectResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateProjectResponse")
    public Status updateProject(
        @WebParam(name = "UpdateProjectRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "UpdateProjectRequest")
        Project updateProjectRequest);

    /**
     * 
     * @param deleteProjectVersionRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "DeleteProjectVersion")
    @WebResult(name = "DeleteProjectVersionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteProjectVersionResponse")
    public Status deleteProjectVersion(
        @WebParam(name = "DeleteProjectVersionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "DeleteProjectVersionRequest")
        DeleteProjectVersionRequest deleteProjectVersionRequest);

    /**
     * 
     * @param runtimeApplicationListRequest
     * @return
     *     returns com.fortify.schema.fws.RuntimeApplicationListResponse
     */
    @WebMethod(operationName = "RuntimeApplicationList")
    @WebResult(name = "RuntimeApplicationListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RuntimeApplicationListResponse")
    public RuntimeApplicationListResponse runtimeApplicationList(
        @WebParam(name = "RuntimeApplicationListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RuntimeApplicationListRequest")
        Object runtimeApplicationListRequest);

    /**
     * 
     * @param assignCustomTagsToProjectVersionRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "AssignCustomTagsToProjectVersion")
    @WebResult(name = "AssignCustomTagsToProjectVersionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AssignCustomTagsToProjectVersionResponse")
    public Status assignCustomTagsToProjectVersion(
        @WebParam(name = "AssignCustomTagsToProjectVersionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AssignCustomTagsToProjectVersionRequest")
        AssignCustomTagsToProjectVersionRequest assignCustomTagsToProjectVersionRequest);

    /**
     * 
     * @param createAlertDefinitionForSelfRequest
     */
    @WebMethod(operationName = "CreateAlertDefinitionForSelf")
    @Oneway
    public void createAlertDefinitionForSelf(
        @WebParam(name = "CreateAlertDefinitionForSelfRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CreateAlertDefinitionForSelfRequest")
        CreateAlertDefinitionForSelfRequest createAlertDefinitionForSelfRequest);

    /**
     * 
     * @param verifyCloudOneTimeJobTokenRequest
     * @return
     *     returns com.fortify.schema.fws.VerifyCloudOneTimeJobTokenResponse
     */
    @WebMethod(operationName = "VerifyCloudOneTimeJobToken")
    @WebResult(name = "VerifyCloudOneTimeJobTokenResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "VerifyCloudOneTimeJobTokenResponse")
    public VerifyCloudOneTimeJobTokenResponse verifyCloudOneTimeJobToken(
        @WebParam(name = "VerifyCloudOneTimeJobTokenRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "VerifyCloudOneTimeJobTokenRequest")
        Object verifyCloudOneTimeJobTokenRequest);

    /**
     * 
     * @param performAuditActionRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "PerformAuditAction")
    @WebResult(name = "PerformAuditActionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "PerformAuditActionResponse")
    public Status performAuditAction(
        @WebParam(name = "PerformAuditActionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "PerformAuditActionRequest")
        PerformAuditActionRequest performAuditActionRequest);

    /**
     * 
     * @param addProjectRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.AddStatus
     */
    @WebMethod(operationName = "AddProject")
    @WebResult(name = "AddProjectResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddProjectResponse")
    public AddStatus addProject(
        @WebParam(name = "AddProjectRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddProjectRequest")
        Project addProjectRequest);

    /**
     * 
     * @param ldapEntityDeleteRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "LdapEntityDelete")
    @WebResult(name = "LdapEntityDeleteResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "LdapEntityDeleteResponse")
    public Status ldapEntityDelete(
        @WebParam(name = "LdapEntityDeleteRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "LdapEntityDeleteRequest")
        LdapEntityDeleteRequest ldapEntityDeleteRequest);

    /**
     * 
     * @param checkCurrentUserPermissionRequest
     * @return
     *     returns com.fortify.schema.fws.CheckCurrentUserPermissionResponse
     */
    @WebMethod(operationName = "CheckCurrentUserPermission")
    @WebResult(name = "CheckCurrentUserPermissionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CheckCurrentUserPermissionResponse")
    public CheckCurrentUserPermissionResponse checkCurrentUserPermission(
        @WebParam(name = "CheckCurrentUserPermissionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CheckCurrentUserPermissionRequest")
        CheckCurrentUserPermissionRequest checkCurrentUserPermissionRequest);

    /**
     * 
     * @param runtimeEventArchiveListRequest
     * @return
     *     returns com.fortify.schema.fws.RuntimeEventArchiveListResponse
     */
    @WebMethod(operationName = "RuntimeEventArchiveList")
    @WebResult(name = "RuntimeEventArchiveListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RuntimeEventArchiveListResponse")
    public RuntimeEventArchiveListResponse runtimeEventArchiveList(
        @WebParam(name = "RuntimeEventArchiveListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RuntimeEventArchiveListRequest")
        Object runtimeEventArchiveListRequest);

    /**
     * 
     * @param variableHistoryListRequest
     * @return
     *     returns com.fortify.schema.fws.VariableHistoryListResponse
     */
    @WebMethod(operationName = "VariableHistoryList")
    @WebResult(name = "VariableHistoryListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "VariableHistoryListResponse")
    public VariableHistoryListResponse variableHistoryList(
        @WebParam(name = "VariableHistoryListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "VariableHistoryListRequest")
        VariableHistoryListRequest variableHistoryListRequest);

    /**
     * 
     * @param filterSetsAndFoldersUpdateRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "FilterSetsAndFoldersUpdate")
    @WebResult(name = "FilterSetsAndFoldersUpdateResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "FilterSetsAndFoldersUpdateResponse")
    public Status filterSetsAndFoldersUpdate(
        @WebParam(name = "FilterSetsAndFoldersUpdateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "FilterSetsAndFoldersUpdateRequest")
        FilterSetsAndFoldersUpdateRequest filterSetsAndFoldersUpdateRequest);

    /**
     * 
     * @param alertDefinitionByIdRequest
     */
    @WebMethod(operationName = "AlertDefinitionById")
    @Oneway
    public void alertDefinitionById(
        @WebParam(name = "AlertDefinitionByIdRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AlertDefinitionByIdRequest")
        AlertDefinitionByIdRequest alertDefinitionByIdRequest);

    /**
     * 
     * @param addProjectAndVersionRequest
     * @return
     *     returns com.fortify.schema.fws.AddProjectAndVersionResponse
     */
    @WebMethod(operationName = "AddProjectAndVersion")
    @WebResult(name = "AddProjectAndVersionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddProjectAndVersionResponse")
    public AddProjectAndVersionResponse addProjectAndVersion(
        @WebParam(name = "AddProjectAndVersionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddProjectAndVersionRequest")
        AddProjectAndVersionRequest addProjectAndVersionRequest);

    /**
     * 
     * @param invalidateAuditSessionRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "InvalidateAuditSession")
    @WebResult(name = "InvalidateAuditSessionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "InvalidateAuditSessionResponse")
    public Status invalidateAuditSession(
        @WebParam(name = "InvalidateAuditSessionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "InvalidateAuditSessionRequest")
        InvalidateAuditSessionRequest invalidateAuditSessionRequest);

    /**
     * 
     * @param reportDefinitionByIDRequest
     */
    @WebMethod(operationName = "ReportDefinitionByID")
    @Oneway
    public void reportDefinitionByID(
        @WebParam(name = "ReportDefinitionByIDRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ReportDefinitionByIDRequest")
        ReportDefinitionByIdRequest reportDefinitionByIDRequest);

    /**
     * 
     * @param customTagListRequest
     * @return
     *     returns com.fortify.schema.fws.CustomTagListResponse
     */
    @WebMethod(operationName = "CustomTagList")
    @WebResult(name = "CustomTagListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CustomTagListResponse")
    public CustomTagListResponse customTagList(
        @WebParam(name = "CustomTagListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "CustomTagListRequest")
        CustomTagListRequest customTagListRequest);

    /**
     * 
     * @param reportDefinitionByNameRequest
     */
    @WebMethod(operationName = "ReportDefinitionByName")
    @Oneway
    public void reportDefinitionByName(
        @WebParam(name = "ReportDefinitionByNameRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "ReportDefinitionByNameRequest")
        ReportDefinitionByNameRequest reportDefinitionByNameRequest);

    /**
     * 
     * @param restoreRuntimeEventRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "RestoreRuntimeEvent")
    @WebResult(name = "RestoreRuntimeEventResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RestoreRuntimeEventResponse")
    public Status restoreRuntimeEvent(
        @WebParam(name = "RestoreRuntimeEventRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "RestoreRuntimeEventRequest")
        RestoreRuntimeEventRequest restoreRuntimeEventRequest);

    /**
     * 
     * @param sourceArchiveUploadRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "SourceArchiveUpload")
    @WebResult(name = "SourceArchiveUploadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SourceArchiveUploadResponse")
    public Status sourceArchiveUpload(
        @WebParam(name = "SourceArchiveUploadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SourceArchiveUploadRequest")
        SourceArchiveUploadRequest sourceArchiveUploadRequest);

    /**
     * 
     * @param snapshotsForProjectVersionAndDateRequest
     */
    @WebMethod(operationName = "SnapshotsForProjectVersionAndDate")
    @Oneway
    public void snapshotsForProjectVersionAndDate(
        @WebParam(name = "SnapshotsForProjectVersionAndDateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SnapshotsForProjectVersionAndDateRequest")
        SnapshotsForProjectVersionAndDateRequest snapshotsForProjectVersionAndDateRequest);

    /**
     * 
     * @param genericRequest
     * @return
     *     returns com.fortify.schema.fws.GenericResponse
     */
    @WebMethod(operationName = "Generic")
    @WebResult(name = "GenericResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "GenericResponse")
    public GenericResponse generic(
        @WebParam(name = "GenericRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "GenericRequest")
        Status genericRequest);

    /**
     * 
     * @param performanceIndicatorListRequest
     * @return
     *     returns com.fortify.schema.fws.PerformanceIndicatorListResponse
     */
    @WebMethod(operationName = "PerformanceIndicatorList")
    @WebResult(name = "PerformanceIndicatorListResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "PerformanceIndicatorListResponse")
    public PerformanceIndicatorListResponse performanceIndicatorList(
        @WebParam(name = "PerformanceIndicatorListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "PerformanceIndicatorListRequest")
        Object performanceIndicatorListRequest);

    /**
     * 
     * @param historicalDataMigrateRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.Status
     */
    @WebMethod(operationName = "HistoricalDataMigrate")
    @WebResult(name = "HistoricalDataMigrateResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "HistoricalDataMigrateResponse")
    public Status historicalDataMigrate(
        @WebParam(name = "HistoricalDataMigrateRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "HistoricalDataMigrateRequest")
        HistoricalDataMigrateRequest historicalDataMigrateRequest);

    /**
     * 
     * @param getSingleUseFPRUploadTokenRequest
     */
    @WebMethod(operationName = "GetSingleUseFPRUploadToken")
    @Oneway
    public void getSingleUseFPRUploadToken(
        @WebParam(name = "GetSingleUseFPRUploadTokenRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "GetSingleUseFPRUploadTokenRequest")
        GetSingleUseFprUploadTokenRequest getSingleUseFPRUploadTokenRequest);

    /**
     * 
     * @param addProjectVersionRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.AddStatus
     */
    @WebMethod(operationName = "AddProjectVersion")
    @WebResult(name = "AddProjectVersionResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddProjectVersionResponse")
    public AddStatus addProjectVersion(
        @WebParam(name = "AddProjectVersionRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "AddProjectVersionRequest")
        AddProjectVersionRequest addProjectVersionRequest);

    /**
     * 
     * @param sdlBundleUploadRequest
     * @return
     *     returns xmlns.www_fortifysoftware_com.schema.wstypes.SdlBundleUploadStatus
     */
    @WebMethod(operationName = "SDLBundleUpload")
    @WebResult(name = "SDLBundleUploadResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SDLBundleUploadResponse")
    public SdlBundleUploadStatus sdlBundleUpload(
        @WebParam(name = "SDLBundleUploadRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "SDLBundleUploadRequest")
        SdlBundleUploadRequest sdlBundleUploadRequest);

    /**
     * 
     * @param findLdapUserDNRequest
     * @return
     *     returns com.fortify.schema.fws.FindLdapUserDnResponse
     */
    @WebMethod(operationName = "FindLdapUserDN")
    @WebResult(name = "FindLdapUserDNResponse", targetNamespace = "http://www.fortify.com/schema/fws", partName = "FindLdapUserDNResponse")
    public FindLdapUserDnResponse findLdapUserDN(
        @WebParam(name = "FindLdapUserDNRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "FindLdapUserDNRequest")
        String findLdapUserDNRequest);

    /**
     * 
     * @param mostRecentMeasurementHistoryListRequest
     */
    @WebMethod(operationName = "MostRecentMeasurementHistoryList")
    @Oneway
    public void mostRecentMeasurementHistoryList(
        @WebParam(name = "MostRecentMeasurementHistoryListRequest", targetNamespace = "http://www.fortify.com/schema/fws", partName = "MostRecentMeasurementHistoryListRequest")
        MostRecentMeasurementHistoryListRequest mostRecentMeasurementHistoryListRequest);

}
