
package com.fortify.schema.fws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-hudson-$BUILD_NUMBER-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "servicesService", targetNamespace = "http://www.fortify.com/schema/fws", wsdlLocation = "https://raw.github.com/simonbrandhof/fortify-cxf-client/master/src/main/resources/fws.wsdl")
public class ServicesService
    extends Service
{

    private final static URL SERVICESSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.fortify.schema.fws.ServicesService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.fortify.schema.fws.ServicesService.class.getResource(".");
            url = new URL(baseUrl, "https://raw.github.com/simonbrandhof/fortify-cxf-client/master/src/main/resources/fws.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://raw.github.com/simonbrandhof/fortify-cxf-client/master/src/main/resources/fws.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICESSERVICE_WSDL_LOCATION = url;
    }

    public ServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicesService() {
        super(SERVICESSERVICE_WSDL_LOCATION, new QName("http://www.fortify.com/schema/fws", "servicesService"));
    }

    /**
     * 
     * @return
     *     returns Services
     */
    @WebEndpoint(name = "servicesSoap11")
    public Services getServicesSoap11() {
        return super.getPort(new QName("http://www.fortify.com/schema/fws", "servicesSoap11"), Services.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Services
     */
    @WebEndpoint(name = "servicesSoap11")
    public Services getServicesSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.fortify.com/schema/fws", "servicesSoap11"), Services.class, features);
    }

}
